set check_function_bodies = off;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone not null default timezone('utc'::text, now())
);

alter table public.categories enable row level security;

drop policy if exists categories_select_all on public.categories;
create policy categories_select_all
  on public.categories
  for select
  using (true);

revoke all on table public.categories from anon, authenticated;
grant select on table public.categories to anon, authenticated;
grant all on table public.categories to service_role;

insert into public.categories (id, name)
values
  (1, 'tarea'),
  (2, 'estudio'),
  (3, 'fisico'),
  (4, 'social'),
  (5, 'finanzas'),
  (6, 'entretenimiento'),
  (7, 'salud'),
  (8, 'trabajo'),
  (9, 'nutricion'),
  (10, 'hogar'),
  (11, 'otros')
on conflict (id) do update
set name = excluded.name;

select setval(
  pg_get_serial_sequence('public.categories', 'id'),
  (select max(id) from public.categories)
);

alter table public.punishments
  drop constraint if exists punishments_category_check;

alter table public.punishments
  drop constraint if exists punishments_catalog_consistency_check;

alter table public.punishments
  rename column category to category_legacy_name;

alter table public.punishments
  add column category bigint;

with category_backfill as (
  select punishment_row.id,
         case
           when punishment_row.title = 'Sin redes sociales' then 6
           when punishment_row.title = 'Camina 8000 pasos' then 3
           when punishment_row.title = 'Ordena el escritorio' then 8
           when punishment_row.title = 'Leer 20 paginas' then 2
           when punishment_row.title = 'Dormir sin pantallas' then 7
           when punishment_row.title = '50 flexiones' then 3
           when punishment_row.title = 'Limpia una habitacion' then 10
           when punishment_row.title = 'Donar 5 EUR' then 5
           when punishment_row.title = 'Sin cafe manana' then 7
           when punishment_row.title = 'Preparar comida sana' then 9
           when punishment_row.title = 'Escribir reflexion' then 2
           when punishment_row.title = 'Plancha 3 minutos' then 3
           when punishment_row.title = 'Bloque profundo' then 8
           when punishment_row.title = 'Correr 5 km' then 3
           when punishment_row.title = 'Limpieza profunda cocina' then 10
           when punishment_row.title = 'Donar 15 EUR' then 5
           when punishment_row.title = 'Sin streaming 48h' then 6
           when punishment_row.title = 'Sesion de movilidad 40 min' then 7
           when punishment_row.title = 'Vaciar bandeja pendiente' then 1
           when punishment_row.title = 'Lavar y doblar ropa' then 10
           when punishment_row.category_legacy_name = 'physical' then 3
           when punishment_row.category_legacy_name = 'financial' then 5
           when punishment_row.category_legacy_name = 'domestic' then 10
           when punishment_row.category_legacy_name = 'productive' then 1
           else 11
         end as category_id
  from public.punishments punishment_row
)
update public.punishments punishment_row
set category = category_backfill.category_id
from category_backfill
where punishment_row.id = category_backfill.id;

update public.punishments
set category = 11
where category is null;

alter table public.punishments
  alter column category set not null;

alter table public.punishments
  add constraint punishments_category_fkey
  foreign key (category)
  references public.categories(id)
  on update restrict
  on delete restrict;

create index if not exists punishments_category_idx
  on public.punishments (category);

alter table public.punishments
  add constraint punishments_catalog_consistency_check
  check (
    ((owner_id is null) and (is_custom = false))
    or ((owner_id is not null) and (is_custom = true))
  );

alter table public.punishments
  drop column category_legacy_name;

drop function if exists public.get_home_summary();

create function public.get_home_summary()
returns table (
  active_goals_count integer,
  pending_punishments_count integer,
  latest_pending_assigned_id uuid,
  latest_pending_goal_id uuid,
  latest_pending_punishment_id uuid,
  latest_pending_due_date date,
  latest_pending_status text,
  latest_punishment_title text,
  latest_punishment_description text,
  latest_punishment_category_id bigint,
  latest_punishment_category_name text,
  latest_punishment_difficulty smallint,
  latest_punishment_scope text
)
language sql
security invoker
set search_path = public
as $$
  with current_context as (
    select auth.uid() as user_id
  )
  select coalesce((
           select count(*)
           from public.goals goal_row
           where goal_row.user_id = current_context.user_id
             and goal_row.active
         ), 0)::integer as active_goals_count,
         coalesce((
           select count(*)
           from public.assigned_punishments assigned_row
           where assigned_row.user_id = current_context.user_id
             and assigned_row.status = 'pending'
         ), 0)::integer as pending_punishments_count,
         latest_pending.id as latest_pending_assigned_id,
         latest_pending.goal_id as latest_pending_goal_id,
         latest_pending.punishment_id as latest_pending_punishment_id,
         latest_pending.due_date as latest_pending_due_date,
         latest_pending.status as latest_pending_status,
         latest_pending.title as latest_punishment_title,
         latest_pending.description as latest_punishment_description,
         latest_pending.category_id as latest_punishment_category_id,
         latest_pending.category_name as latest_punishment_category_name,
         latest_pending.difficulty as latest_punishment_difficulty,
         latest_pending.scope as latest_punishment_scope
  from current_context
  left join lateral (
    select assigned_row.id,
           assigned_row.goal_id,
           assigned_row.punishment_id,
           assigned_row.due_date,
           assigned_row.status,
           punishment_row.title,
           punishment_row.description,
           punishment_row.category as category_id,
           category_row.name as category_name,
           punishment_row.difficulty,
           case when punishment_row.owner_id is null then 'base' else 'personal' end as scope
    from public.assigned_punishments assigned_row
    join public.punishments punishment_row on punishment_row.id = assigned_row.punishment_id
    join public.categories category_row on category_row.id = punishment_row.category
    where assigned_row.user_id = current_context.user_id
      and assigned_row.status = 'pending'
    order by assigned_row.assigned_at desc, assigned_row.id desc
    limit 1
  ) latest_pending on true;
$$;

drop function if exists public.list_punishment_catalog();

create function public.list_punishment_catalog()
returns table (
  id uuid,
  title text,
  description text,
  category_id bigint,
  category_name text,
  difficulty smallint,
  scope text,
  created_at timestamp with time zone
)
language sql
security invoker
set search_path = public
as $$
  select punishment_row.id,
         punishment_row.title,
         punishment_row.description,
         punishment_row.category as category_id,
         category_row.name as category_name,
         punishment_row.difficulty,
         case when punishment_row.owner_id is null then 'base' else 'personal' end as scope,
         punishment_row.created_at
  from public.punishments punishment_row
  join public.categories category_row on category_row.id = punishment_row.category
  where punishment_row.owner_id is null
     or punishment_row.owner_id = auth.uid()
  order by case when punishment_row.owner_id is null then 1 else 0 end,
           punishment_row.created_at desc,
           punishment_row.id desc;
$$;

drop function if exists public.list_pending_punishments();

create function public.list_pending_punishments()
returns table (
  assigned_id uuid,
  goal_id uuid,
  goal_title text,
  punishment_id uuid,
  punishment_title text,
  punishment_description text,
  punishment_category_id bigint,
  punishment_category_name text,
  punishment_difficulty smallint,
  punishment_scope text,
  assigned_at timestamp with time zone,
  due_date date,
  status text
)
language sql
security invoker
set search_path = public
as $$
  select assigned_row.id as assigned_id,
         assigned_row.goal_id,
         goal_row.title as goal_title,
         punishment_row.id as punishment_id,
         punishment_row.title as punishment_title,
         punishment_row.description as punishment_description,
         punishment_row.category as punishment_category_id,
         category_row.name as punishment_category_name,
         punishment_row.difficulty as punishment_difficulty,
         case when punishment_row.owner_id is null then 'base' else 'personal' end as punishment_scope,
         assigned_row.assigned_at,
         assigned_row.due_date,
         assigned_row.status
  from public.assigned_punishments assigned_row
  inner join public.goals goal_row on goal_row.id = assigned_row.goal_id
  inner join public.punishments punishment_row on punishment_row.id = assigned_row.punishment_id
  inner join public.categories category_row on category_row.id = punishment_row.category
  where assigned_row.user_id = auth.uid()
    and assigned_row.status = 'pending'
  order by assigned_row.assigned_at desc, assigned_row.id desc;
$$;

revoke all on function public.get_home_summary() from public;
revoke all on function public.list_punishment_catalog() from public;
revoke all on function public.list_pending_punishments() from public;

grant execute on function public.get_home_summary() to authenticated, service_role;
grant execute on function public.list_punishment_catalog() to authenticated, service_role;
grant execute on function public.list_pending_punishments() to authenticated, service_role;
